apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.connectionName }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.connectionName }}
  selector:
{{ include "app.match-labels" . | indent 4 }}
